/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as DashIndexRouteImport } from './routes/_dash.index'
import { Route as DashOrdenesRouteImport } from './routes/_dash.ordenes'
import { Route as DashMapaRouteImport } from './routes/_dash.mapa'
import { Route as DashKpisRouteImport } from './routes/_dash.kpis'
import { Route as DashInventarioRouteImport } from './routes/_dash.inventario'
import { Route as DashConfiguracionRouteImport } from './routes/_dash.configuracion'
import { Route as DashAlertasRouteImport } from './routes/_dash.alertas'

const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRoute,
} as any)
const DashOrdenesRoute = DashOrdenesRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => DashRoute,
} as any)
const DashMapaRoute = DashMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => DashRoute,
} as any)
const DashKpisRoute = DashKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => DashRoute,
} as any)
const DashInventarioRoute = DashInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => DashRoute,
} as any)
const DashConfiguracionRoute = DashConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => DashRoute,
} as any)
const DashAlertasRoute = DashAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashIndexRoute
  '/alertas': typeof DashAlertasRoute
  '/configuracion': typeof DashConfiguracionRoute
  '/inventario': typeof DashInventarioRoute
  '/kpis': typeof DashKpisRoute
  '/mapa': typeof DashMapaRoute
  '/ordenes': typeof DashOrdenesRoute
}
export interface FileRoutesByTo {
  '/alertas': typeof DashAlertasRoute
  '/configuracion': typeof DashConfiguracionRoute
  '/inventario': typeof DashInventarioRoute
  '/kpis': typeof DashKpisRoute
  '/mapa': typeof DashMapaRoute
  '/ordenes': typeof DashOrdenesRoute
  '/': typeof DashIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dash': typeof DashRouteWithChildren
  '/_dash/alertas': typeof DashAlertasRoute
  '/_dash/configuracion': typeof DashConfiguracionRoute
  '/_dash/inventario': typeof DashInventarioRoute
  '/_dash/kpis': typeof DashKpisRoute
  '/_dash/mapa': typeof DashMapaRoute
  '/_dash/ordenes': typeof DashOrdenesRoute
  '/_dash/': typeof DashIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/configuracion'
    | '/inventario'
    | '/kpis'
    | '/mapa'
    | '/ordenes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/alertas'
    | '/configuracion'
    | '/inventario'
    | '/kpis'
    | '/mapa'
    | '/ordenes'
    | '/'
  id:
    | '__root__'
    | '/_dash'
    | '/_dash/alertas'
    | '/_dash/configuracion'
    | '/_dash/inventario'
    | '/_dash/kpis'
    | '/_dash/mapa'
    | '/_dash/ordenes'
    | '/_dash/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashRoute: typeof DashRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/': {
      id: '/_dash/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/ordenes': {
      id: '/_dash/ordenes'
      path: '/ordenes'
      fullPath: '/ordenes'
      preLoaderRoute: typeof DashOrdenesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/mapa': {
      id: '/_dash/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof DashMapaRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/kpis': {
      id: '/_dash/kpis'
      path: '/kpis'
      fullPath: '/kpis'
      preLoaderRoute: typeof DashKpisRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/inventario': {
      id: '/_dash/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof DashInventarioRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/configuracion': {
      id: '/_dash/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof DashConfiguracionRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/alertas': {
      id: '/_dash/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof DashAlertasRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashAlertasRoute: typeof DashAlertasRoute
  DashConfiguracionRoute: typeof DashConfiguracionRoute
  DashInventarioRoute: typeof DashInventarioRoute
  DashKpisRoute: typeof DashKpisRoute
  DashMapaRoute: typeof DashMapaRoute
  DashOrdenesRoute: typeof DashOrdenesRoute
  DashIndexRoute: typeof DashIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashAlertasRoute: DashAlertasRoute,
  DashConfiguracionRoute: DashConfiguracionRoute,
  DashInventarioRoute: DashInventarioRoute,
  DashKpisRoute: DashKpisRoute,
  DashMapaRoute: DashMapaRoute,
  DashOrdenesRoute: DashOrdenesRoute,
  DashIndexRoute: DashIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashRoute: DashRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
