/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as DashIndexRouteImport } from './routes/_dash.index'
import { Route as DashVehiculosV2RouteImport } from './routes/_dash.vehiculos-v2'
import { Route as DashOrdenesV2RouteImport } from './routes/_dash.ordenes-v2'
import { Route as DashInventarioV2RouteImport } from './routes/_dash.inventario-v2'
import { Route as DashHomeRouteImport } from './routes/_dash.home'
import { Route as DashConfiguracionRouteImport } from './routes/_dash.configuracion'
import { Route as DashAlertasRouteImport } from './routes/_dash.alertas'

const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRoute,
} as any)
const DashVehiculosV2Route = DashVehiculosV2RouteImport.update({
  id: '/vehiculos-v2',
  path: '/vehiculos-v2',
  getParentRoute: () => DashRoute,
} as any)
const DashOrdenesV2Route = DashOrdenesV2RouteImport.update({
  id: '/ordenes-v2',
  path: '/ordenes-v2',
  getParentRoute: () => DashRoute,
} as any)
const DashInventarioV2Route = DashInventarioV2RouteImport.update({
  id: '/inventario-v2',
  path: '/inventario-v2',
  getParentRoute: () => DashRoute,
} as any)
const DashHomeRoute = DashHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashRoute,
} as any)
const DashConfiguracionRoute = DashConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => DashRoute,
} as any)
const DashAlertasRoute = DashAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashIndexRoute
  '/alertas': typeof DashAlertasRoute
  '/configuracion': typeof DashConfiguracionRoute
  '/home': typeof DashHomeRoute
  '/inventario-v2': typeof DashInventarioV2Route
  '/ordenes-v2': typeof DashOrdenesV2Route
  '/vehiculos-v2': typeof DashVehiculosV2Route
}
export interface FileRoutesByTo {
  '/alertas': typeof DashAlertasRoute
  '/configuracion': typeof DashConfiguracionRoute
  '/home': typeof DashHomeRoute
  '/inventario-v2': typeof DashInventarioV2Route
  '/ordenes-v2': typeof DashOrdenesV2Route
  '/vehiculos-v2': typeof DashVehiculosV2Route
  '/': typeof DashIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dash': typeof DashRouteWithChildren
  '/_dash/alertas': typeof DashAlertasRoute
  '/_dash/configuracion': typeof DashConfiguracionRoute
  '/_dash/home': typeof DashHomeRoute
  '/_dash/inventario-v2': typeof DashInventarioV2Route
  '/_dash/ordenes-v2': typeof DashOrdenesV2Route
  '/_dash/vehiculos-v2': typeof DashVehiculosV2Route
  '/_dash/': typeof DashIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/configuracion'
    | '/home'
    | '/inventario-v2'
    | '/ordenes-v2'
    | '/vehiculos-v2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/alertas'
    | '/configuracion'
    | '/home'
    | '/inventario-v2'
    | '/ordenes-v2'
    | '/vehiculos-v2'
    | '/'
  id:
    | '__root__'
    | '/_dash'
    | '/_dash/alertas'
    | '/_dash/configuracion'
    | '/_dash/home'
    | '/_dash/inventario-v2'
    | '/_dash/ordenes-v2'
    | '/_dash/vehiculos-v2'
    | '/_dash/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashRoute: typeof DashRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/': {
      id: '/_dash/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/vehiculos-v2': {
      id: '/_dash/vehiculos-v2'
      path: '/vehiculos-v2'
      fullPath: '/vehiculos-v2'
      preLoaderRoute: typeof DashVehiculosV2RouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/ordenes-v2': {
      id: '/_dash/ordenes-v2'
      path: '/ordenes-v2'
      fullPath: '/ordenes-v2'
      preLoaderRoute: typeof DashOrdenesV2RouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/inventario-v2': {
      id: '/_dash/inventario-v2'
      path: '/inventario-v2'
      fullPath: '/inventario-v2'
      preLoaderRoute: typeof DashInventarioV2RouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/home': {
      id: '/_dash/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof DashHomeRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/configuracion': {
      id: '/_dash/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof DashConfiguracionRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/alertas': {
      id: '/_dash/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof DashAlertasRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashAlertasRoute: typeof DashAlertasRoute
  DashConfiguracionRoute: typeof DashConfiguracionRoute
  DashHomeRoute: typeof DashHomeRoute
  DashInventarioV2Route: typeof DashInventarioV2Route
  DashOrdenesV2Route: typeof DashOrdenesV2Route
  DashVehiculosV2Route: typeof DashVehiculosV2Route
  DashIndexRoute: typeof DashIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashAlertasRoute: DashAlertasRoute,
  DashConfiguracionRoute: DashConfiguracionRoute,
  DashHomeRoute: DashHomeRoute,
  DashInventarioV2Route: DashInventarioV2Route,
  DashOrdenesV2Route: DashOrdenesV2Route,
  DashVehiculosV2Route: DashVehiculosV2Route,
  DashIndexRoute: DashIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashRoute: DashRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
